export enum ProfileActionTypes {
    API_RESPONSE_SUCCESS = '@@profile/API_RESPONSE_SUCCESS',
    API_RESPONSE_ERROR = '@@profile/API_RESPONSE_ERROR',

    GET_PROFILE = '@@profile/GET_PROFILE',
    UPDATE_PROFILE = '@@profile/UPDATE_PROFILE',
    UPDATE_PROFILE_PASSWORD = '@@profile/UPDATE_PROFILE_PASSWORD',

    RESET_PROFILE_MESSAGES = '@@profile/RESET_PROFILE_MESSAGES',
    RESET_PROFILE = '@@profile/RESET_PROFILE'
}
